### PR TITLE
Mark directories with trailing slash when globing

### LINKED ISSUE #111: tab completions don't insert trailing / for directories.
We need to understand where trailing / and bold comes from when readline displays our completions.

The default completions should be disabled, so I have either made a mistake, or the library does some post processing of our completions.

### PR DESCRIPTION
**Pull request by ALSchwalm**
Fixes #111 (I think)

I'm not entirely sure from the issue description if this is sufficient to close it, but this will cause directory completions to show the trailing '/'.

### CODE REVIEW

**Comment by ALSchwalm** [comment]
Not sure what's going on there, but these failures don't seem related to this pr

**Comment by andrewchambers** [comment]
The failures are a bug in sr.ht. I have reported in earlier. I removed '/' from your PR title.

**Comment by andrewchambers** [comment]
Hmm strange, I had this change in before and my tab completions showed double trailing slash.

**Comment by andrewchambers** [comment]
@ALSchwalm  Something is still wrong, when I enable this patch, completions are being chopped short:

```
[ac@black:~/src/janetsh/src] $ ./
./anetsh                ./anetsh-posix-wrapper  ./eadnoise/             ./h.janet               ./hlib.so               ./hlib/                 ./osixsh.janet
```

The bug is certainly in my code, I just didn't have time to investigate. If you have an inclination to investigate, I will be very grateful, otherwise I can't merge until I have time to investigate.

**Comment by ALSchwalm** [comment]
Oh I see. Yeah, that's an issue. I'll take a look

**Comment by andrewchambers** [comment]
@ALSchwalm in shlib.c The bug may potentially be in shlib_readline_attempted_completion_function (but maybe not), the documentation of that interface for gnu readline was a bit scarce.

**Comment by andrewchambers** [comment]
Closing for now, feel free to reopen with new changes.

**Pull request closed without merging**
