### PR TITLE
Argument-less `cd` changes dir to $HOME

### LINKED ISSUE #109: cd with no args should default to $HOME

### PR DESCRIPTION
**Pull request by x4lldux**
Resolves #109

### CODE REVIEW

**Comment by x4lldux** [comment]
Strange, is FreeBSD build vm missing HOME variable?

**Comment by andrewchambers** [comment]
sr.ht is a relatively new service - I expect they are changing things and made a mistake.

**Comment by andrewchambers** [comment]
@X4lldux 

Awesome work - if freebsd doesn't have home, I guess you could just set it in the test case with os/setenv. A bit hacky, but probably ok for now.

A better solution may be a more reliable way to find a user home, perhaps something in shlib, but we don't need to worry about that for now.

**Comment by x4lldux** [comment]
@andrewchambers I guess I can add a nicer error when it croaks & add hardcode env in test.

Even bash's version of `cd` depends on $HOME so using a different way is just over complicating it to fix an obscure edge case.

**Comment by andrewchambers** [comment]
That would be great. Thank you so much.

**Pull request merged**
